; PlatformIO Project Configuration File
[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0

lib_deps = 
    esphome/ESP32-audioI2S @ ^2.0.7
    blynkkk/Blynk@^1.3.2
    
build_flags =
    -O2                  # Ottimizzazione bilanciata
    -mlongcalls          # Obbligatorio per ESP32
    -Wl,-u,setup -Wl,-u,loop  # Forza il linker a cercare setup()/loop()
    -DUSE_ARDUINO_FRAMEWORK
    -DUSE_I2S_DRIVER=1

src_filter = +<*.cpp> +<*.c>  # Supporta sia C che C++